clc;
clear;
global rect_position;
global rect_move_start_point;
rect_position = [1,1,1,1];
rect_move_start_point = [1,1];
image_path = './12-orig.jpg';
image = imread(image_path);
figure_handle = figure(1);
imshow(image, []);
hold on;
mouse_track(figure_handle);
